name: post_repository
description: Dart package witch manages the post


publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  uuid: ^4.2.1
  # bloc
  equatable: ^2.0.5
 
  # firebase
  cloud_firestore: ^4.13.2


  user_repository:
    path: ../user_repository
  
dev_dependencies:
  flutter_test:
    sdk: flutter
 
  
  flutter_lints: ^2.0.0

flutter:
 
  uses-material-design: true